pipeline {
  agent any
  stages {
    stage('scm checkout') {
      steps {
        git 'https://github.com/Pranavhatkar/maven-project.git' //this is generated by syntax generated 
      }
    }

    stage('Package job') //validate + compile +test +package
    {
      steps {
        withMaven(jdk: 'JDK HOME', maven: 'MVN HOME', traceability: true) {
         sh 'mvn package' /// this step we have to write 
          }
        }
      }
    /* stage('Deploy to tomacat server') // this tep created by pipline syntax gen by ssh agent 
    {
      steps {
        sshagent(['DEV_CICD']) {
             sh '''
        scp -o StrictHostKeyChecking=no \
        webapp/target/webapp.war \
        ec2-user@172.31.12.14:/opt/tomcat/webapps/
    '''}
        }
      } */
    }
}
