pipeline {
  agent any
  stages {
    stage('scm checkout') {
      steps {
        git 'https://github.com/Pranavhatkar/maven-project.git' //this is generated by syntax generated 
      }
    }

    stage('Package job') //validate + compile +test +package
    {
      steps {
        withMaven(jdk: 'JDK HOME', maven: 'MVN HOME', traceability: true) {
         sh 'mvn package' /// this step we have to write 
          }
        }
      }
     stage('Deploy to tomcat server') {
    steps {
        sshagent(['ec2-user']) {
            sh '''
                scp -o StrictHostKeyChecking=no webapp/target/webapp.war ec2-user@172.31.12.14:/tmp/
                ssh -o StrictHostKeyChecking=no ec2-user@172.31.12.14 "sudo mv /tmp/webapp.war /opt/tomcat/webapps/"
            '''
           }
          }
         }
        }
    }
